### ISSUE TITLE
Could the authors provide REC code?

### ISSUE THREAD

**Issue by QiuHeqian** [rentainhe/TRAR-VQA#1]
Hello, 

I am very interested in your work.  I noticed that the authors have conducted experiments on REC datasets (RefCOCO, RefCOCO+, RefCOCOg).However, I only find the code about VQA datasets (VQA2.0 and CLEVR), could you provide this code of this part?

Thank you!

**Comment by rentainhe** [comment]
We will release our TRAR-REC code in https://github.com/luogen1996/SimREC, however we are still developing this repo~

**Comment by QiuHeqian** [comment]
Could you consider providing me with the code of this part about how you implement REC in your paper? It will help us to reproduce even without complete and beautiful SimREC for me. Thank you!

**Comment by rentainhe** [comment]
> Could you consider providing me with the code of this part about how you implement REC in your paper? It will help us to reproduce even without complete and beautiful SimREC for me. Thank you!

oh, it may takes us some time to add the corresponding code to SimREC, please wait for some time~, we will release it as soon as possible.

**Comment by QiuHeqian** [comment]
Thank you for your careful reply. We look forward to your code.

**Comment by rentainhe** [comment]
> Thank you for your careful reply. We look forward to your code.

Thank you for your appreciation of our work~, we will release our REC baseline as soon as possible
