### ISSUE TITLE
求助TRAR相关的问题

### ISSUE THREAD

**Issue by MissionAbort** [rentainhe/TRAR-VQA#3]
尊敬的TRAR作者，您好，我最近也在训练TRAR模型，在超参数基本同您一致的情况下，采用了您仓库中所提供的 8x8 Grid features数据集，经过多次训练，我的模型准确度大概在71.5%（VQA2.0）左右，达不到您在文中所提出的为72%，
另外，我也加载了您所提供的train+val+vg->test预训练模型参数，并在这个数据集上只能跑到70.6%（VQA2.0），综上，请问是因为这个8x8网格特征的问题吗？或者还是其他原因？
期待您的答复，谢谢。

**Comment by rentainhe** [comment]
> 尊敬的TRAR作者，您好，我最近也在训练TRAR模型，在超参数基本同您一致的情况下，采用了您仓库中所提供的 8x8 Grid features数据集，经过多次训练，我的模型准确度大概在71.5%（VQA2.0）左右，达不到您在文中所提出的为72%， 另外，我也加载了您所提供的train+val+vg->test预训练模型参数，并在这个数据集上只能跑到70.6%（VQA2.0），综上，请问是因为这个8x8网格特征的问题吗？或者还是其他原因？ 期待您的答复，谢谢。

有一个trick你可以参考一下，就是先在train+val+vg上训练完后，从10epochs开始在train+val上finetune一下，这样会提升结果，应该可以达到72

**Comment by MissionAbort** [comment]
> > 尊敬的TRAR作者，您好，我最近也在训练TRAR模型，在超参数基本同您一致的情况下，采用了您仓库中所提供的 8x8 Grid features数据集，经过多次训练，我的模型准确度大概在71.5%（VQA2.0）左右，达不到您在文中所提出的为72%， 另外，我也加载了您所提供的train+val+vg->test预训练模型参数，并在这个数据集上只能跑到70.6%（VQA2.0），综上，请问是因为这个8x8网格特征的问题吗？或者还是其他原因？ 期待您的答复，谢谢。
> 
> 有一个trick你可以参考一下，就是先在train+val+vg上训练完后，从10epochs开始在train+val上finetune一下，这样会提升结果，应该可以达到72

已顺利解决，感谢大佬！

**Comment by rentainhe** [comment]
> > > 尊敬的TRAR作者，您好，我最近也在训练TRAR模型，在超参数基本同您一致的情况下，采用了您仓库中所提供的 8x8 Grid features数据集，经过多次训练，我的模型准确度大概在71.5%（VQA2.0）左右，达不到您在文中所提出的为72%， 另外，我也加载了您所提供的train+val+vg->test预训练模型参数，并在这个数据集上只能跑到70.6%（VQA2.0），综上，请问是因为这个8x8网格特征的问题吗？或者还是其他原因？ 期待您的答复，谢谢。
> > 
> > 
> > 有一个trick你可以参考一下，就是先在train+val+vg上训练完后，从10epochs开始在train+val上finetune一下，这样会提升结果，应该可以达到72
> 
> 已顺利解决，感谢大佬！

好的，能复现就好！
